name: Build and upload binaries to release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  github:
    name: Publish Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          persist-credentials: false

      - name: Upload binary to release
        run: gh release
