name: Build and upload binaries to release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  github:
    name: Publish Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          persist-credentials: false

      - name: Upload binary to release
        run: gh release
