name: Build and upload binaries to release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  github:
    name: Publish Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Upload binary to release
        run: gh release
